### ISSUE TITLE
apilocation needs to be HTTPS or CSS/JS break

### ISSUE THREAD

**Issue by paperscissors** [cashmusic/rackspace-template#27]
I haven't been able to verify this because email isn't working, but I believe the API location needs to be https on here in order for CSS and JS to load.

so 
apilocation = "http://localhost/api/"

needs to be
apilocation = "https://vagrant-multi1.cashmusic.org/api/"

grain of salt.

**Comment by paperscissors** [comment]
verified at least the admin login dialog renders correctly with JS to boot, after changing these values and vagrant reload ing

**Comment by jeffsheltren** [comment]
I think #28 should be enough to fix this, let me know if something else is needed.  Thanks!
