### ISSUE TITLE
simplify error log output?

### ISSUE THREAD

**Issue by paperscissors** [cashmusic/rackspace-template#34]
@jeffsheltren @jessevondoom possible to have a simplified general error log in the vagrant setup deploy?

right now it's the usually PHP-FPM super verbose stuff like

`[Thu Jun 09 18:23:57 2016] [error] [client 10.10.10.1] FastCGI: server "/usr/sbin/php-fpm-www" stderr:`

which makes debugging stuff like printed arrays a bit of a mess. Thanks!

**Comment by jeffsheltren** [comment]
I'm not sure if there's much I can do for the Apache/FastCGI output; I'd recommend starting with the PHP error log instead.

I merged #38 to reduce the noise in the PHP error log (/var/log/php-fpm/error.log).  How's that look?
