### ISSUE TITLE
allow access to user subdomains/dirs on box

### ISSUE THREAD

**Issue by paperscissors** [cashmusic/rackspace-template#35]
So usually on the platform you can head to myusername.cashmusic.org, or cashmusic.org/myusername and you can see your page view; you can't do this on the vagrant box though. It just forwards to the front page of the CASH site (on the local box). Any way to allow this so we can test page view locally?

**Comment by jeffsheltren** [comment]
I'm unable to test right now, but if you edit your local /etc/hosts file to point to the VM IP address, I believe that should work fine for any subdomain.  Could you give that a try?

**Comment by paperscissors** [comment]
Yup, that's the answer--- is that something we can add to the vagrant-hostsupdater call? Adding in dev.vagrant-multi1.cashmusic.org in addition to vagrant-multi1.cashmusic.org for default?

Awesome!

**Comment by jeffsheltren** [comment]
I merged #39 to add a configuration for this.  You'll need to copy the new block from `Vagrantfile.local.example`, and you can use that to set an array of hostnames to be auto-added to /etc/hosts.
