### ISSUE TITLE
The requested URL returned error: 503

### ISSUE THREAD

**Issue by hdchantre** [cashmusic/rackspace-template#58]
Hi there,
I am new here, and looking to learn how the platform work.
But it seems the link to download the virtual box are not working.
The requested URL returned error: 503

Any Help?
Regards

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'centos67-x86_64-20150830-puppet-3.8.2-vbox-guest-additions-5.0.2.box' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'centos67-x86_64-20150830-puppet-3.8.2-vbox-guest-additions-5.0.2.box' (v0) for provider: virtualbox
    default: Downloading: https://pkg.tag1consulting.com/vagrant-boxes/centos6-50GB-vbguest/centos67-x86_64-20150830-puppet-3.8.2-vbox-guest-additions-5.0.2.box
    default: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 503

**Comment by jeffsheltren** [comment]
Hi @hdchantre unfortunately this is pretty unmaintained at this point. You could probably get by using a default `centos/6` Vagrant box, and manually adding Puppet and the Virtualbox guest additions (or use a vagrant plugin for the latter) -- assuming you're comfortable messing around with the `Vagrantfile` config.
